[build]
  command = "rm -rf node_modules package-lock.json && npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_BASE_PATH = ""
  NEXT_TELEMETRY_DISABLED = ""
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs" 